import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { routes } from '../../core.index';
import { an } from '@fullcalendar/core/internal-common';

@Injectable({
  providedIn: 'root',
})
export class SidebarService {
  constructor() {
    if (localStorage.getItem('sideBarPosition') == 'expand') {
      this.expandSideBar.next(true);
    } else {
      this.expandSideBar.next(false);
    }
  }

  public sideBarPosition: BehaviorSubject<string> = new BehaviorSubject<string>(
    localStorage.getItem('sideBarPosition') || 'false'
  );

  public toggleMobileSideBar: BehaviorSubject<any> = new BehaviorSubject<any>(
    localStorage.getItem('isMobileSidebar') || false
  );

  public expandSideBar: BehaviorSubject<any> = new BehaviorSubject<any>(false);

  public switchSideMenuPosition(): void {
    if (localStorage.getItem('sideBarPosition')) {
      this.sideBarPosition.next('false');
      this.expandSideBar.next(true);
      localStorage.removeItem('sideBarPosition');
    } else {
      this.sideBarPosition.next('true');
      this.expandSideBar.next(false);
      localStorage.setItem('sideBarPosition', 'true');
    }
  }

  public switchMobileSideBarPosition(): void {
    if (localStorage.getItem('isMobileSidebar')) {
      this.toggleMobileSideBar.next(false);
      localStorage.removeItem('isMobileSidebar');
    } else {
      this.toggleMobileSideBar.next(true);
      localStorage.setItem('isMobileSidebar', 'true');
    }
  }

  private sidebarData: Array<any> = [
    {
      tittle: 'Main Menu',
      hasSubRoute: true,
      icon: 'assets/img/icons/menu-icon.svg',
      showSubRoute: false,
      route: '',
      activeRoute: '',
      subRoutes: [
        {
          tittle: 'Dashboard',
          hasSubRoute: false,
          icon: 'assets/img/icons/dashboard.svg',
          showSubRoute: false,
          route: routes.dashboard,
          activeRoute: this.getActiveRoute(routes.dashboard),
          subRoutes: [],
        },
        {
          tittle: 'Product',
          hasSubRoute: true,
          icon: 'assets/img/icons/product.svg',
          showSubRoute: false,
          route: routes.product,
          activeRoute: this.getActiveRoute(routes.product),
          subRoutes: [
            {
              tittle: 'Product List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.productList,
              activeRoute: this.getActiveRoute(routes.productList),
              subRoutes: [],
            },
            {
              tittle: 'Add Product',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addProduct,
              activeRoute: this.getActiveRoute(routes.addProduct),
              subRoutes: [],
            },
            {
              tittle: 'Category List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.categoryList,
              activeRoute: this.getActiveRoute(routes.categoryList),
              subRoutes: [],
            },
            {
              tittle: 'Add Category',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addCategory,
              activeRoute: this.getActiveRoute(routes.addCategory),
              subRoutes: [],
            },
            {
              tittle: 'Sub Category List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.subCategoryList,
              activeRoute: this.getActiveRoute(routes.subCategoryList),
              subRoutes: [],
            },
            {
              tittle: 'Add Sub Category',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addSubcategory,
              activeRoute: this.getActiveRoute(routes.addSubcategory),
              subRoutes: [],
            },
            {
              tittle: 'Brand List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.brandList,
              activeRoute: this.getActiveRoute(routes.brandList),
              subRoutes: [],
            },
            {
              tittle: 'Import Products',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.importProduct,
              activeRoute: this.getActiveRoute(routes.importProduct),
              subRoutes: [],
            },
            {
              tittle: 'Print Barcode',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.barcode,
              activeRoute: this.getActiveRoute(routes.barcode),
              subRoutes: [],
            },
          ],
        },
        {
          tittle: 'Sales',
          hasSubRoute: true,
          icon: 'assets/img/icons/sales1.svg',
          showSubRoute: false,
          route: routes.sales,
          activeRoute: this.getActiveRoute(routes.sales),
          subRoutes: [
            {
              tittle: 'Sales List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.salesList,
              activeRoute: this.getActiveRoute(routes.salesList),
              subRoutes: [],
            },
            {
              tittle: 'POS',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.pos,
              activeRoute: this.getActiveRoute(routes.pos),
              subRoutes: [],
            },
            {
              tittle: 'New Sales',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addSales,
              activeRoute: this.getActiveRoute(routes.addSales),
              subRoutes: [],
            },
            {
              tittle: 'Sales Return List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.salesReturnList,
              activeRoute: this.getActiveRoute(routes.salesReturnList),
              subRoutes: [],
            },
            {
              tittle: 'New Sales Return',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.createSalesReturn,
              activeRoute: this.getActiveRoute(routes.createSalesReturn),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Purchase',
          hasSubRoute: true,
          icon: 'assets/img/icons/purchase1.svg',
          showSubRoute: false,
          route: routes.purchase,
          activeRoute: this.getActiveRoute(routes.purchase),
          subRoutes: [
            {
              tittle: 'Purchase List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.purchaseList,
              activeRoute: this.getActiveRoute(routes.purchaseList),
              subRoutes: [],
            },
            {
              tittle: 'Add Purchase',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addPurchase,
              activeRoute: this.getActiveRoute(routes.addPurchase),
              subRoutes: [],
            },
            {
              tittle: 'Import Purchase',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.importPurchase,
              activeRoute: this.getActiveRoute(routes.importPurchase),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Expense',
          hasSubRoute: true,
          icon: 'assets/img/icons/expense1.svg',
          showSubRoute: false,
          route: routes.expense,
          activeRoute: this.getActiveRoute(routes.expense),
          subRoutes: [
            {
              tittle: 'Expense List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.expenseList,
              activeRoute: this.getActiveRoute(routes.expenseList),
              subRoutes: [],
            },
            {
              tittle: 'Add Expense',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.createExpense,
              activeRoute: this.getActiveRoute(routes.createExpense),
              subRoutes: [],
            },
            {
              tittle: 'Expense Category',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.expenseCategory,
              activeRoute: this.getActiveRoute(routes.expenseCategory),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Quotation',
          hasSubRoute: true,
          icon: 'assets/img/icons/quotation1.svg',
          showSubRoute: false,
          route: routes.quotation,
          activeRoute: this.getActiveRoute(routes.quotation),
          subRoutes: [
            {
              tittle: 'Quotation List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.quotationList,
              activeRoute: this.getActiveRoute(routes.quotationList),
              subRoutes: [],
            },
            {
              tittle: 'Add Quotation',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addQuotation,
              activeRoute: this.getActiveRoute(routes.addQuotation),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Transfer',
          hasSubRoute: true,
          icon: 'assets/img/icons/transfer1.svg',
          showSubRoute: false,
          route: routes.transfer,
          activeRoute: this.getActiveRoute(routes.transfer),
          subRoutes: [
            {
              tittle: 'Transfer List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.transferList,
              activeRoute: this.getActiveRoute(routes.transferList),
              subRoutes: [],
            },
            {
              tittle: 'Add Transfer',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addTransfer,
              activeRoute: this.getActiveRoute(routes.addTransfer),
              subRoutes: [],
            },
            {
              tittle: 'Import Transfer',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.importTransfer,
              activeRoute: this.getActiveRoute(routes.importTransfer),
              subRoutes: [],
            },
          ],
        },
        {
          tittle: 'Return',
          hasSubRoute: true,
          icon: 'assets/img/icons/return1.svg',
          showSubRoute: false,
          route: routes.return,
          activeRoute: this.getActiveRoute(routes.return),
          subRoutes: [
            {
              tittle: 'Sales Return List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.salesReturnList,
              activeRoute: this.getActiveRoute(routes.salesReturnList),
              subRoutes: [],
            },
            {
              tittle: 'Add Sales Return',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.createSalesReturn,
              activeRoute: this.getActiveRoute(routes.createSalesReturn),
              subRoutes: [],
            },
            {
              tittle: 'Purchase Return List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.purchaseReturnList,
              activeRoute: this.getActiveRoute(routes.purchaseReturnList),
              subRoutes: [],
            },
            {
              tittle: 'Add Purchase Return',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.createPurchaseReturn,
              activeRoute: this.getActiveRoute(routes.createPurchaseReturn),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'People',
          hasSubRoute: true,
          icon: 'assets/img/icons/users1.svg',
          showSubRoute: false,
          route: routes.people,
          activeRoute: this.getActiveRoute(routes.people),
          subRoutes: [
            {
              tittle: 'Customer List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.customerList,
              activeRoute: this.getActiveRoute(routes.customerList),
              subRoutes: [],
            },
            {
              tittle: 'Add Customer',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addCustomer,
              activeRoute: this.getActiveRoute(routes.addCustomer),
              subRoutes: [],
            },
            {
              tittle: 'Supplier List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.supplierList,
              activeRoute: this.getActiveRoute(routes.supplierList),
              subRoutes: [],
            },
            {
              tittle: 'Add Supplier',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addSupplier,
              activeRoute: this.getActiveRoute(routes.addSupplier),
              subRoutes: [],
            },
            {
              tittle: 'User List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.userList,
              activeRoute: this.getActiveRoute(routes.userList),
              subRoutes: [],
            },
            {
              tittle: 'Add User',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addUser,
              activeRoute: this.getActiveRoute(routes.addUser),
              subRoutes: [],
            },
            {
              tittle: 'Store List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.storeList,
              activeRoute: this.getActiveRoute(routes.storeList),
              subRoutes: [],
            },
            {
              tittle: 'Add Store',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.addStore,
              activeRoute: this.getActiveRoute(routes.addStore),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Places',
          hasSubRoute: true,
          icon: 'assets/img/icons/places.svg',
          showSubRoute: false,
          route: routes.places,
          activeRoute: this.getActiveRoute(routes.places),
          subRoutes: [
            {
              tittle: 'New Country',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.newCountry,
              activeRoute: this.getActiveRoute(routes.newCountry),
              subRoutes: [],
            },
            {
              tittle: 'Countries list',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.countriesList,
              activeRoute: this.getActiveRoute(routes.countriesList),
              subRoutes: [],
            },
            {
              tittle: 'New State',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.newState,
              activeRoute: this.getActiveRoute(routes.newState),
              subRoutes: [],
            },
            {
              tittle: 'State List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.stateList,
              activeRoute: this.getActiveRoute(routes.stateList),
              subRoutes: [],
            },
          ],
        },
      ],
    },

    {
      tittle: 'Users',
      hasSubRoute: true,
      icon: 'assets/img/icons/users1.svg',
      showSubRoute: false,
      route: '',
      activeRoute: 'users',
      subRoutes: [
        {
          tittle: 'New User',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.newUser,
          activeRoute: this.getActiveRoute(routes.newUser),
          subRoutes: [],
        },
        {
          tittle: 'User List',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.usersUserList,
          activeRoute: this.getActiveRoute(routes.usersUserList),
          subRoutes: [],
        },
      ],
    },

    {
      tittle: 'Components',
      hasSubRoute: true,
      icon: 'assets/img/icons/layers.svg',
      showSubRoute: false,
      route: '',
      activeRoute: '',
      subRoutes: [
        {
          tittle: 'Components',
          hasSubRoute: false,
          icon: 'assets/img/icons/layers.svg',
          showSubRoute: false,
          route: routes.components,
          activeRoute: this.getActiveRoute(routes.components),
          subRoutes: [],
        },
        {
          tittle: 'Elements',
          hasSubRoute: true,
          icon: 'assets/img/icons/box.svg',
          showSubRoute: false,
          route: routes.element,
          activeRoute: this.getActiveRoute(routes.element),
          subRoutes: [
            {
              tittle: 'Sweet Alerts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.sweetAlerts,
              activeRoute: this.getActiveRoute(routes.sweetAlerts),
              subRoutes: [],
            },
            {
              tittle: 'Tooltip',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.tooltip,
              activeRoute: this.getActiveRoute(routes.tooltip),
              subRoutes: [],
            },
            {
              tittle: 'Popover',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.popover,
              activeRoute: this.getActiveRoute(routes.popover),
              subRoutes: [],
            },
            {
              tittle: 'Ribbon',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.ribbon,
              activeRoute: this.getActiveRoute(routes.ribbon),
              subRoutes: [],
            },
            {
              tittle: 'Clipboard',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.clipboard,
              activeRoute: this.getActiveRoute(routes.clipboard),
              subRoutes: [],
            },
            {
              tittle: 'Drag & Drop',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.dragDrop,
              activeRoute: this.getActiveRoute(routes.dragDrop),
              subRoutes: [],
            },
            {
              tittle: 'Range Slider',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.rangeSlider,
              activeRoute: this.getActiveRoute(routes.rangeSlider),
              subRoutes: [],
            },
            {
              tittle: 'Rating',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.rating,
              activeRoute: this.getActiveRoute(routes.rating),
              subRoutes: [],
            },
            {
              tittle: 'Toaster',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.toaster,
              activeRoute: this.getActiveRoute(routes.toaster),
              subRoutes: [],
            },

            {
              tittle: 'Text Editor',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.textEditor,
              activeRoute: this.getActiveRoute(routes.textEditor),
              subRoutes: [],
            },
            {
              tittle: 'Counter',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.counter,
              activeRoute: this.getActiveRoute(routes.counter),
              subRoutes: [],
            },
            {
              tittle: 'Scrollbar',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.scrollbar,
              activeRoute: this.getActiveRoute(routes.scrollbar),
              subRoutes: [],
            },
            {
              tittle: 'Spinner',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.spinner,
              activeRoute: this.getActiveRoute(routes.spinner),
              subRoutes: [],
            },
            {
              tittle: 'Notification',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.notification,
              activeRoute: this.getActiveRoute(routes.notification),
              subRoutes: [],
            },
            {
              tittle: 'Lightbox',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.lightbox,
              activeRoute: this.getActiveRoute(routes.lightbox),
              subRoutes: [],
            },
            {
              tittle: 'Timeline',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.timeline,
              activeRoute: this.getActiveRoute(routes.timeline),
              subRoutes: [],
            },
            {
              tittle: 'Form Wizard',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formWizard,
              activeRoute: this.getActiveRoute(routes.formWizard),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Charts',
          hasSubRoute: true,
          icon: 'assets/img/icons/bar-chart-2.svg',
          showSubRoute: false,
          route: routes.charts,
          activeRoute: this.getActiveRoute(routes.charts),
          subRoutes: [
            {
              tittle: 'Apex Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartApex,
              activeRoute: this.getActiveRoute(routes.chartApex),
              subRoutes: [],
            },
            {
              tittle: 'Ng2 Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartNg2,
              activeRoute: this.getActiveRoute(routes.chartNg2),
              subRoutes: [],
            },
            {
              tittle: 'Prime NG Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartPrime,
              activeRoute: this.getActiveRoute(routes.chartPrime),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Icons',
          hasSubRoute: true,
          icon: 'assets/img/icons/award.svg',
          showSubRoute: false,
          route: routes.icons,
          activeRoute: this.getActiveRoute(routes.icons),
          subRoutes: [
            {
              tittle: 'Fontawesome Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFontAwesome,
              activeRoute: this.getActiveRoute(routes.iconFontAwesome),
              subRoutes: [],
            },
            {
              tittle: 'Feather Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFeather,
              activeRoute: this.getActiveRoute(routes.iconFeather),
              subRoutes: [],
            },
            {
              tittle: 'Ionic Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconIonic,
              activeRoute: this.getActiveRoute(routes.iconIonic),
              subRoutes: [],
            },
            {
              tittle: 'Material Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconMaterial,
              activeRoute: this.getActiveRoute(routes.iconMaterial),
              subRoutes: [],
            },
            {
              tittle: 'Pe7 Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconPe7,
              activeRoute: this.getActiveRoute(routes.iconPe7),
              subRoutes: [],
            },
            {
              tittle: 'Simpleline Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconSimpleline,
              activeRoute: this.getActiveRoute(routes.iconSimpleline),
              subRoutes: [],
            },
            {
              tittle: 'Themify Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconThemify,
              activeRoute: this.getActiveRoute(routes.iconThemify),
              subRoutes: [],
            },
            {
              tittle: 'Weather Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconWeather,
              activeRoute: this.getActiveRoute(routes.iconWeather),
              subRoutes: [],
            },
            {
              tittle: 'Typicon Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconTypicon,
              activeRoute: this.getActiveRoute(routes.iconTypicon),
              subRoutes: [],
            },
            {
              tittle: 'Flag Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFlag,
              activeRoute: this.getActiveRoute(routes.iconFlag),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Forms',
          hasSubRoute: true,
          icon: 'assets/img/icons/columns.svg',
          showSubRoute: false,
          route: routes.forms,
          activeRoute: this.getActiveRoute(routes.forms),
          subRoutes: [
            {
              tittle: 'Basic Inputs',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formBasicInputs,
              activeRoute: this.getActiveRoute(routes.formBasicInputs),
              subRoutes: [],
            },
            {
              tittle: 'Input Groups',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formInputsGroups,
              activeRoute: this.getActiveRoute(routes.formInputsGroups),
              subRoutes: [],
            },
            {
              tittle: 'Horizontal Form',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formHorizontal,
              activeRoute: this.getActiveRoute(routes.formHorizontal),
              subRoutes: [],
            },
            {
              tittle: 'Vertical Form',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formVertical,
              activeRoute: this.getActiveRoute(routes.formVertical),
              subRoutes: [],
            },
            {
              tittle: 'Form Mask',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formMask,
              activeRoute: this.getActiveRoute(routes.formMask),
              subRoutes: [],
            },
            {
              tittle: 'Form Validation',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formValidation,
              activeRoute: this.getActiveRoute(routes.formValidation),
              subRoutes: [],
            },
            {
              tittle: 'Form Select',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formSelect,
              activeRoute: this.getActiveRoute(routes.formSelect),
              subRoutes: [],
            },
          ],
        },

        {
          tittle: 'Table',
          hasSubRoute: true,
          icon: 'assets/img/icons/layout.svg',
          showSubRoute: false,
          route: routes.table,
          activeRoute: this.getActiveRoute(routes.table),
          subRoutes: [
            {
              tittle: 'Basic Tables',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.basicTable,
              activeRoute: this.getActiveRoute(routes.basicTable),
              subRoutes: [],
            },
            {
              tittle: 'Data Tables',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.dataTable,
              activeRoute: this.getActiveRoute(routes.dataTable),
              subRoutes: [],
            },
          ],
        },
        {
          tittle: 'Blank Page',
          hasSubRoute: false,
          icon: 'assets/img/icons/file.svg',
          showSubRoute: false,
          route: routes.blankPage,
          activeRoute: this.getActiveRoute(routes.blankPage),
          subRoutes: [],
        },
        {
          tittle: 'Error Pages',
          hasSubRoute: true,
          icon: 'assets/img/icons/alert-octagon.svg',
          showSubRoute: false,
          route: routes.errorPages,
          activeRoute: this.getActiveRoute(routes.errorPages),
          subRoutes: [
            {
              tittle: '404 Error',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.errorPage404,
              activeRoute: this.getActiveRoute(routes.errorPage404),
              subRoutes: [],
            },
            {
              tittle: '500 Error',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.errorPage500,
              activeRoute: this.getActiveRoute(routes.errorPage500),
              subRoutes: [],
            },
          ],
        },
      ],
    },

    {
      tittle: 'Application',
      hasSubRoute: true,
      icon: 'assets/img/icons/product.svg',
      showSubRoute: false,
      route: routes.application,
      activeRoute: this.getActiveRoute(routes.application),
      subRoutes: [
        {
          tittle: 'Chat',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.chat,
          activeRoute: this.getActiveRoute(routes.chat),
          subRoutes: [],
        },
        {
          tittle: 'Calendar',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.calendar,
          activeRoute: this.getActiveRoute(routes.calendar),
          subRoutes: [],
        },
        {
          tittle: 'Email',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.email,
          activeRoute: this.getActiveRoute(routes.email),
          subRoutes: [],
        },
      ],
    },

    {
      tittle: 'Report',
      hasSubRoute: true,
      icon: 'assets/img/icons/time.svg',
      showSubRoute: false,
      route: routes.report,
      activeRoute: this.getActiveRoute(routes.report),
      subRoutes: [
        {
          tittle: 'Purchase order report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.purchaseOrderReport,
          activeRoute: this.getActiveRoute(routes.purchaseOrderReport),
          subRoutes: [],
        },
        {
          tittle: 'Inventory Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.inventoryReport,
          activeRoute: this.getActiveRoute(routes.inventoryReport),
          subRoutes: [],
        },
        {
          tittle: 'Sales Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.salesReport,
          activeRoute: this.getActiveRoute(routes.salesReport),
          subRoutes: [],
        },
        {
          tittle: 'Invoice Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.invoiceReport,
          activeRoute: this.getActiveRoute(routes.invoiceReport),
          subRoutes: [],
        },
        {
          tittle: 'Purchase Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.purchaseReport,
          activeRoute: this.getActiveRoute(routes.purchaseReport),
          subRoutes: [],
        },
        {
          tittle: 'Supplier Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.supplierReport,
          activeRoute: this.getActiveRoute(routes.supplierReport),
          subRoutes: [],
        },
        {
          tittle: 'Customer Report',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.customerReport,
          activeRoute: this.getActiveRoute(routes.customerReport),
          subRoutes: [],
        },
      ],
    },

    {
      tittle: 'Settings',
      hasSubRoute: true,
      icon: 'assets/img/icons/settings.svg',
      showSubRoute: false,
      route: routes.settings,
      activeRoute: this.getActiveRoute(routes.settings),
      subRoutes: [
        {
          tittle: 'General Settings',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.generalSettings,
          activeRoute: this.getActiveRoute(routes.generalSettings),
          subRoutes: [],
        },
        {
          tittle: 'Email Settings',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.emailSettings,
          activeRoute: this.getActiveRoute(routes.emailSettings),
          subRoutes: [],
        },
        {
          tittle: 'Payment Settings',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.paymentSettings,
          activeRoute: this.getActiveRoute(routes.paymentSettings),
          subRoutes: [],
        },
        {
          tittle: 'Currency Settings',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.currencySettings,
          activeRoute: this.getActiveRoute(routes.currencySettings),
          subRoutes: [],
        },
        {
          tittle: 'Group Permissions',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.groupSettings,
          activeRoute: this.getActiveRoute(routes.groupSettings),
          subRoutes: [],
        },
        {
          tittle: 'Tax Rates',
          hasSubRoute: false,
          icon: '',
          showSubRoute: false,
          route: routes.taxRates,
          activeRoute: this.getActiveRoute(routes.taxRates),
          subRoutes: [],
        },
      ],
    },
  ];

  public getSideBarData :BehaviorSubject<Array<any>> = new BehaviorSubject<Array<any>>(this.sidebarData)
  getActiveRoute(route: string): string {
    let url = route.split('/');
    return url[url.length - 1];
  }

  private sidebarDataone: Array<any> = [
    {
      tittle: 'Main',
      showAsTab: true,
      separateRoute: false,
      menu: [
        {
          menuValue: 'Dashboard',
          route: routes.dashboard,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'grid',
          base: 'dashboard',
          subMenus: []
        },
        {
          menuValue: 'Application',
          route: routes.application,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'smartphone',
          base: 'application',
          subMenus: [
            {
              menuValue: 'Chat',
              route: routes.chat,
              page: 'chat',
            },
            {
              menuValue: 'Calendar',
              hasSubRoute: false,
              showSubRoute: false,
              route: routes.calendar,
              page: 'calendar',
              subRoutes: [],
            },
            {
              menuValue: 'Email',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.email,
              page: 'email',
              subRoutes: [],
            },
          ],
        },
      ]
    },
    {
      tittle: 'Products',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Products',
          route: routes.productList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'box',
          page: 'product-list',
          subMenus: []
        },
        {
          menuValue: 'Create Product',
          route: routes.addProduct,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'plus-square',
          page: 'add-product',
          subMenus: []
        },
        {
          menuValue: 'Category',
          route: routes.categoryList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'codepen',
          page: 'category-list',
          subMenus: []
        },
        {
          menuValue: 'Brands',
          route: routes.brandList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'tag',
          page: 'brand-list',
          subMenus: []
        },
        {
          menuValue: 'Sub Category',
          route: routes.subCategoryList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'speaker',
          page: 'sub-category-list',
          subMenus: []
        },
        {
          menuValue: 'Print Barcode',
          route: routes.barcode,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'align-justify',
          page: 'barcode',
          subMenus: []
        },
        {
          menuValue: 'Import Products',
          route: routes.importProduct,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'minimize-2',
          page: 'import-product',
          subMenus: []
        },
      ]
    },
    {
      tittle: 'Sales',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Sales',
          route: routes.salesList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'shopping-cart',
          page: 'sales-list',
          subMenus: []
        },
        {
          menuValue: 'Invoices',
          route: routes.invoiceReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'file-text',
          page: 'invoice-report',
          subMenus: []
        },
        {
          menuValue: 'Sales Return',
          route: routes.salesReturnLists,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'copy',
          page: 'sales-return-lists',
          subMenus: []
        },
        {
          menuValue: 'Quotation',
          route: routes.quotationList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'save',
          page: 'quotation-list',
          subMenus: []
        },
        {
          menuValue: 'POS',
          route: routes.pos,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'hard-drive',
          page: 'pos',
          subMenus: []
        },
        {
          menuValue: 'Transfer',
          route: routes.transfer,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'shuffle',
          base: 'transfer',
          subMenus: [
            {
              menuValue: 'Transfer List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.transferList,
              page: 'transfer-list',
              subRoutes: [],
            },
            {
              menuValue: 'Import Transfer',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.importTransfer,
              page: 'import-transfer',
              subRoutes: [],
            },
          ],
        },
        {
          menuValue: 'Return',
          route: routes.return,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'corner-up-left',
          base: 'return',
          subMenus: [
            {
              menuValue: 'Sales Return',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.salesReturnList,
              page: 'sales-return-list',
              subRoutes: [],
            },
            {
              menuValue: 'Purchase Return',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.purchaseReturnList,
              page: 'purchase-return-list',
              subRoutes: [],
            },
          ],
        },
      ]
    },
    {
      tittle: 'Purchases',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Purchases',
          route: routes.purchaseList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'shopping-bag',
          page: 'purchase-list',
          subMenus: []
        },
        {
          menuValue: 'Import Purchases',
          route: routes.importPurchase,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'minimize-2',
          page: 'import-purchase',
          subMenus: []
        },
        {
          menuValue: 'Purchase Order',
          route: routes.purchaseOrderReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'file-minus',
          page: 'purchase-order-report',
          subMenus: []
        },
        {
          menuValue: 'Purchase Return',
          route: routes.purchaseReturnList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'refresh-cw',
          page: 'purchase-return-list',
          subMenus: []
        },
      ]
    },
    {
      tittle: 'Finance & Accounts',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Expense',
          route: routes.expense,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'file-text',
          base: 'expense',
          subMenus: [
            {
              menuValue: 'Expenses',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.expenseList,
              page: 'expense-list',
              subRoutes: [],
            },
            {
              menuValue: 'Expense Category',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.expenseCategory,
              page: 'expense-category',
              subRoutes: [],
            },
          ],
        },
      ]
    },
    {
      tittle: 'Peoples',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Customers',
          route: routes.customerList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'user',
          page: 'customer-list',
          subMenus: []
        },
        {
          menuValue: 'Suppliers',
          route: routes.supplierList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'users',
          page: 'supplier-list',
          subMenus: []
        },
        {
          menuValue: 'Users',
          route: routes.userList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'user-check',
          page: 'user-list',
          subMenus: []
        },
        {
          menuValue: 'Stores',
          route: routes.storeList,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'home',
          page: 'store-list',
          subMenus: []
        },
      ]
    },
    {
      tittle: 'Reports',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Sales Report',
          route: routes.salesReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'bar-chart-2',
          page: 'sales-report',
          subMenus: []
        },
        {
          menuValue: 'Purchase Report',
          route: routes.purchaseReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'pie-chart',
          page: 'purchase-report',
          subMenus: []
        },
        {
          menuValue: 'Inventory Report',
          route: routes.inventoryReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'credit-card',
          page: 'inventory-report',
          subMenus: []
        },
        {
          menuValue: 'Invoice Report',
          route: routes.invoiceReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'file',
          page: 'invoice-report',
          subMenus: []
        },
        {
          menuValue: 'Purchase Report',
          route: routes.purchaseOrderReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'bar-chart',
          page: 'purchase-order-report',
          subMenus: []
        },
        {
          menuValue: 'Supplier Report',
          route: routes.supplierReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'database',
          page: 'supplier-report',
          subMenus: []
        },
        {
          menuValue: 'Customer Report',
          route: routes.customerReport,
          hasSubRoute: false,
          showSubRoute: false,
          icon: 'pie-chart',
          page: 'customer-report',
          subMenus: []
        },
      ]
    },
    {
      tittle: 'User Management',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Manage Users',
          route: routes.users,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'users',
          base: 'users',
          subMenus: [
            {
              menuValue: 'New User',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.newUser,
              page: 'new-user',
              subRoutes: [],
            },
            {
              menuValue: 'Users List',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.usersUserList,
              page: 'user-lists',
              subRoutes: [],
            },
          ],
        },
      ]
    },
    {
      tittle: 'Pages',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Authentication',
          route: routes.auth,
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'shield',
          base: 'auth',
          subMenus: [
            {
              menuValue: 'Login',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.signIn,
              page: '',
              subRoutes: [],
            },
            {
              menuValue: 'Register',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.signUp,
              page: '',
              subRoutes: [],
            },
            {
              menuValue: 'Forgot Password',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.forgotPassword,
              page: '',
              subRoutes: [],
            },
            {
              menuValue: 'Reset Password',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.forgotPassword,
              page: '',
              subRoutes: [],
            },
          ],
        },
        {
          menuValue: 'Error Pages',
          hasSubRoute: true,
          showSubRoute: false,
          icon: 'file-minus',
          route: routes.errorPages,
          base: '',
          subMenus: [
            {
              menuValue: '404 Error',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.errorPage404,
              page: '',
              subRoutes: [],
            },
            {
              menuValue: '500 Error',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.errorPage500,
              page: '',
              subRoutes: [],
            },
          ],
        },
        {
          menuValue: 'Places',
          hasSubRoute: true,
          icon: 'map',
          showSubRoute: false,
          route: routes.places,
          base: 'places',
          subMenus: [
            {
              menuValue: 'Countries',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.countriesList,
              page:'countries-list',
              subMenus: [],
            },
            {
              menuValue: 'States',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.stateList,
              page:'state-list',
              subMenus: [],
            },
          ],
        },
        {
          menuValue: 'Blank Page',
          hasSubRoute: false,
          icon: 'file',
          showSubRoute: false,
          route: routes.blankPage,
          page:'blank-page',
          subMenus: [],
        },
        {
          menuValue: 'Components',
          hasSubRoute: false,
          icon: 'hard-drive',
          showSubRoute: false,
          route: routes.components,
          page:'components',
          subMenus: [],
        },
      ]
    },
    {
      tittle: 'UI Interface',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Elements',
          hasSubRoute: true,
          icon: 'layers',
          showSubRoute: false,
          route: routes.element,
          base: 'element',
          subMenus: [
            {
              menuValue: 'Sweet Alerts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.sweetAlerts,
              page:'sweet-alerts',
              subRoutes: [],
            },
            {
              menuValue: 'Tooltip',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.tooltip,
              page:'tooltip',
              subRoutes: [],
            },
            {
              menuValue: 'Popover',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.popover,
              page: 'popover',
              subRoutes: [],
            },
            {
              menuValue: 'Ribbon',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.ribbon,
              page: 'ribbon',
              subRoutes: [],
            },
            {
              menuValue: 'Clipboard',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.clipboard,
              page: 'clipboard',
              subRoutes: [],
            },
            {
              menuValue: 'Drag & Drop',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.dragDrop,
              page: 'drag-drop',
              subRoutes: [],
            },
            {
              menuValue: 'Range Slider',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.rangeSlider,
              page: 'range-slider',
              subRoutes: [],
            },
            {
              menuValue: 'Rating',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.rating,
              page: 'rating',
              subRoutes: [],
            },
            {
              menuValue: 'Toaster',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.toaster,
              page: 'toaster',
              subRoutes: [],
            },

            {
              menuValue: 'Text Editor',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.textEditor,
              page: 'text-editor',
              subRoutes: [],
            },
            {
              menuValue: 'Counter',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.counter,
              page: 'counter',
              subRoutes: [],
            },
            {
              menuValue: 'Scrollbar',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.scrollbar,
              page: 'scrollbar',
              subRoutes: [],
            },
            {
              menuValue: 'Spinner',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.spinner,
              page: 'spinner',
              subRoutes: [],
            },
            {
              menuValue: 'Notification',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.notification,
              page: 'notification',
              subRoutes: [],
            },
            {
              menuValue: 'Lightbox',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.lightbox,
              page: 'lightbox',
              subRoutes: [],
            },
            {
              menuValue: 'Timeline',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.timeline,
              page: 'timeline',
              subRoutes: [],
            },
            {
              menuValue: 'Form Wizard',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formWizard,
              page: 'form-wizard',
              subRoutes: [],
            },
          ],
        },
        {
          menuValue: 'Charts',
          hasSubRoute: true,
          icon: 'bar-chart-2',
          showSubRoute: false,
          route: routes.charts,
          base:'charts',
          subMenus: [
            {
              menuValue: 'Apex Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartApex,
              page: 'chart-apex',
              subRoutes: [],
            },
            {
              menuValue: 'Ng2 Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartNg2,
              page: 'chart-ng2',
              subRoutes: [],
            },
            {
              menuValue: 'Prime NG Charts',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.chartPrime,
              page: 'prime-ng',
              subRoutes: [],
            },
          ],
        },

        {
          menuValue: 'Icons',
          hasSubRoute: true,
          icon: 'database',
          showSubRoute: false,
          route: routes.icons,
          base:'icons',
          subMenus: [
            {
              menuValue: 'Fontawesome Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFontAwesome,
              page: 'icon-fontawesome',
              subRoutes: [],
            },
            {
              menuValue: 'Feather Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFeather,
              page: 'icon-feather',
              subRoutes: [],
            },
            {
              menuValue: 'Ionic Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconIonic,
              page: 'icon-ionic',
              subRoutes: [],
            },
            {
              menuValue: 'Material Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconMaterial,
              page: 'icon-material',
              subRoutes: [],
            },
            {
              menuValue: 'Pe7 Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconPe7,
              page: 'icon-pe7',
              subRoutes: [],
            },
            {
              menuValue: 'Simpleline Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconSimpleline,
              page: 'icon-simpleline',
              subRoutes: [],
            },
            {
              menuValue: 'Themify Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconThemify,
              page: 'icon-themify',
              subRoutes: [],
            },
            {
              menuValue: 'Weather Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconWeather,
              page: 'icon-weather',
              subRoutes: [],
            },
            {
              menuValue: 'Typicon Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconTypicon,
              page: 'icon-typicon',
              subRoutes: [],
            },
            {
              menuValue: 'Flag Icons',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.iconFlag,
              page: 'icon-flag',
              subRoutes: [],
            },
          ],
        },

        {
          menuValue: 'Forms',
          hasSubRoute: true,
          icon: 'edit',
          showSubRoute: false,
          route: routes.forms,
          base: 'forms',
          subMenus: [
            {
              menuValue: 'Basic Inputs',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formBasicInputs,
              page: 'form-basic-inputs',
              subRoutes: [],
            },
            {
              menuValue: 'Input Groups',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formInputsGroups,
              page: 'form-input-groups',
              subRoutes: [],
            },
            {
              menuValue: 'Horizontal Form',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formHorizontal,
              page: 'form-horizontal',
              subRoutes: [],
            },
            {
              menuValue: 'Vertical Form',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formVertical,
              page: 'form-vertical',
              subRoutes: [],
            },
            {
              menuValue: 'Form Mask',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formMask,
              page: 'form-mask',
              subRoutes: [],
            },
            {
              menuValue: 'Form Validation',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formValidation,
              page: 'form-validation',
              subRoutes: [],
            },
            {
              menuValue: 'Form Select',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.formSelect,
              page: 'form-select',
              subRoutes: [],
            },
          ],
        },

        {
          menuValue: 'Table',
          hasSubRoute: true,
          icon: 'user',
          showSubRoute: false,
          route: routes.table,
          base: 'table',
          subMenus: [
            {
              menuValue: 'Basic Tables',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.basicTable,
              page: 'tables-basic',
              subRoutes: [],
            },
            {
              menuValue: 'Data Tables',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.dataTable,
              page: 'data-basic',
              subRoutes: [],
            },
          ],
        },
      ]
    },
    {
      tittle: 'Settings',
      showAsTab: true,
      separateRoute: false,
      menu : [
        {
          menuValue: 'Settings',
          hasSubRoute: true,
          icon: 'settings',
          showSubRoute: false,
          route: routes.settings,
          base: 'settings',
          subMenus: [
            {
              menuValue: 'General Settings',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.generalSettings,
              page: 'general-settings',
              subRoutes: [],
            },
            {
              menuValue: 'Email Settings',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.emailSettings,
              page: 'email-settings',
              subRoutes: [],
            },
            {
              menuValue: 'Payment Settings',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.paymentSettings,
              page: 'payment-settings',
              subRoutes: [],
            },
            {
              menuValue: 'Currency Settings',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.currencySettings,
              page: 'currency-settings',
              subRoutes: [],
            },
            {
              menuValue: 'Group Permissions',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.groupSettings,
              page: 'group-permissions',
              subRoutes: [],
            },
            {
              menuValue: 'Tax Rates',
              hasSubRoute: false,
              icon: '',
              showSubRoute: false,
              route: routes.taxRates,
              page: 'tax-rates',
              subRoutes: [],
            },
          ],
        },
        {
          menuValue: 'Logout',
          hasSubRoute: false,
          icon: 'log-out',
          showSubRoute: false,
          route: routes.signIn,
          subMenus: []
        }
      ]
    }
  ]
  public getSideBarDataone :BehaviorSubject<Array<any>> = new BehaviorSubject<Array<any>>(this.sidebarDataone)
}
